language: python
python:
  - 3.6
jdk:
  - openjdk8
install:
  - pip install pytest-cov pytest
script:
  - update-java-alternatives --list
  - java -version
  - python setup.py install
  - py.test --cov-report term --cov=cogroo_interface
deploy:
  provider: pypi
  user: "$PYPI_USER"
  password:
    secure: "$PYPI_PASSWORD_SECURE"
  skip_cleanup: true
  on:
#    all_branches: true
    branch: master
after_success:
    - codecov
notifications:
  email: false