language: python
python:
  - 3.6
jdk:
  - oraclejdk8
script:
  - python3 setup.py install
deploy:
  provider: pypi
  user: "$PYPI_USER"
  password:
    secure: "$PYPI_PASSWORD_SECURE"
  skip_cleanup: true
  on:
    all_branches: true