language: java
jdk:
  - openjdk8
python:
  - 3.6.7
before_install:
  - pyenv shell 3.6.7
install:
  - pip install pytest-cov pytest
script:
  - python setup.py install
  - py.test --cov-report term --cov=cogroo_interface
deploy:
  provider: pypi
  user: "$PYPI_USER"
  password:
    secure: "$PYPI_PASSWORD_SECURE"
  skip_cleanup: true
  on:
#    all_branches: true
    branch: master
after_success:
  - codecov
notifications:
  email: false