language: python
python:
  - 3.6
addons:
  apt:
    sources:
      - sourceline: 'ppa:openjdk-r/ppa'
    packages:
      - openjdk-8-jre
install:
  - pip install pytest-cov pytest
script:
  - java -version
  - python setup.py install
  - py.test --cov-report term --cov=cogroo_interface
deploy:
  provider: pypi
  user: "$PYPI_USER"
  password:
    secure: "$PYPI_PASSWORD_SECURE"
  skip_cleanup: true
  on:
#    all_branches: true
    branch: master
after_success:
    - codecov
notifications:
  email: false