language: python
python:
  - 3.6
  - pypi3
jdk:
  - oraclejdk8
install:
  - python3 setup.py install
script:
  - python3 setup.py sdist
deploy:
  provider: pypi
  user: "PYPI_USER"
  password:
    secure: "PYPI_PASSWORD_SECURE"
  on:
    all_branches: true